### ISSUE TITLE
Bran var should be "Brain"

### ISSUE THREAD

**Issue by erikng** [scriptingosx/DownloadFullInstaller#1]
Project is very cool. I noticed in the metadata Swift file you have a variable of "bran" and it should be "brain".

I'm mobile so can't send you a PR to fix it myself :)

**Comment by erikng** [comment]
https://github.com/scriptingosx/DownloadFullInstaller/blob/7fd501c55f80fc407adfea4f55f1667d655e41fb/FetchInstallerPkg/Model/MetaInfo.swift#L25

**Comment by scriptingosx** [comment]
Fine eagle eyes there. Thanks! fixed in 652fe29 There is a lot extra code for decoding stuff that I then didn't have to use. I left it in case me (or someone else) wants to use the SUCatalog parsing for something else....
