### ISSUE TITLE
macOS Ventura Beta

### ISSUE THREAD

**Issue by UziKhana** [scriptingosx/DownloadFullInstaller#11]
Would you consider amending this to enable beta downloads too?

**Comment by scriptingosx** [comment]
It already does, check the Preferences window.

**Comment by UziKhana** [comment]
Brilliant!


![Screen Shot 2022-06-29 at 7 21 25 AM](https://user-images.githubusercontent.com/69767649/176344266-565554cf-f279-424d-acbe-e78387d3b8f5.png)


![Screen Shot 2022-06-29 at 7 20 21 AM](https://user-images.githubusercontent.com/69767649/176344295-83d03768-8ca8-4d87-918b-cc957cd5c82c.png)
