### ISSUE TITLE
Can not run on mac os before 11.0

### ISSUE THREAD

**Issue by kingo132** [scriptingosx/DownloadFullInstaller#4]
Hi, thanks for the work, but this app can not run on mac os before Monterey 11.0.
The xcode project can not open as well due to the version limit.
I'm using Catalina, if I can use it in Catalina it should be great, or at least big sur.

**Comment by scriptingosx** [comment]
Yes, the app requires macOS 11 Big Sur (and later). Many of the SwiftUI features it uses are only available in Big Sur (and later). I have no plans to back port it to older versions of macOS. You can use [the python script](https://github.com/scriptingosx/fetch-installer-pkg), the software `softwareupdate` command line tool or [installinstallmacos.py](https://github.com/munki/macadmin-scripts/blob/main/installinstallmacos.py) instead.

Yes, the project was built with Xcode 13 beta, so it won't open in older versions of Xcode. I should probably update the readme to reflect that.
