### ISSUE TITLE
Big Sur seed issues on Monterey

### ISSUE THREAD

**Issue by arsradu** [scriptingosx/DownloadFullInstaller#5]
First of all, congrats on the first release!

Second, could be a bug (looks like a bug), but it doesn't seem to find Big Sur betas, although there should be (11.5 for example).

Also, not sure if this is intended or not, but when selecting Developer Beta seed for example, you still get Big Sur versions that are not from the Beta Seed (final releases) in the list.

**Comment by scriptingosx** [comment]
Unfortunately, I cannot re-create that. It shows the both the 11.5 beta and 12 beta on DeveloperSeed or CustomerSeed for me. Maybe try re-starting the app after choosing a seed. (that would obviously be a bug, but at least it would give me some idea where to look to re-create.)

The app parses Apple's software update feed. Apple lists the "normal" releases in the beta catalogs as well. So it is not really intentional, but I don't plan on changing that.

**Comment by arsradu** [comment]
Got it. Ok, no problem for the mixed updates then. Makes perfect sense not to fix something that's not up to you to fix. :)

However, I keep getting the same issue with Big Sur not displaying all betas... Or...any betas, for that matter. I'm guessing there should be only one: 11.5. But, as you can see in the screenshots below, it's missing from the list.

I'm using the official release. Haven't tried building the app for myself, since I don't have Xcode installed right now. So, all the testing has been done on the official first release.

One thing that could be different is that I'm using this on Monterey. I don't see why this would make a difference...but, well, I still can't see Big Sur betas.

Also, there doesn't seem to be any issue with the refresh (though I could be wrong, of course). Switching from Developer to Customer and Public seems to be refreshing the list just fine. But...it's not showing all the results, for some reason. And it's the same even after restarting the app. I also tried moving the app to the /Applications folder, thinking it would make a difference. Unfortunately, it didn't. Whether it's running from /Desktop or /Applications, the issue is still there.

Attached screenshots, in case it helps. :)
<img width="601" alt="Screenshot 2021-06-25 at 11 57 01" src="https://user-images.githubusercontent.com/86431007/123399370-34fd3500-d5ad-11eb-985f-92c17c5dee59.png">
<img width="601" alt="Screenshot 2021-06-25 at 11 56 43" src="https://user-images.githubusercontent.com/86431007/123399389-3af31600-d5ad-11eb-8efd-49f0af93bda6.png">
<img width="599" alt="Screenshot 2021-06-25 at 11 55 15" src="https://user-images.githubusercontent.com/86431007/123399415-40506080-d5ad-11eb-8940-036ba405bdb9.png">

**Comment by scriptingosx** [comment]
Running on Monterey might explain it. I have not been able to test this on Monterey myself, yet.

Since macOS considers the Monterey beta to supercede the 11.5 beta, I am not surprised you don't see it.

I will keep an eye out for this when I get a Monterey test machine.

**Comment by arsradu** [comment]
Yeeep, looks like the issue is specific to Monterey. I've got Big Sur running on another partition, so I was able to test there, as well.
It's confirmed. This seems to only occur with Monterey.
<img width="599" alt="Screenshot 2021-06-25 at 12 17 31" src="https://user-images.githubusercontent.com/86431007/123401461-7ee71a80-d5af-11eb-9fcb-5dca4311d2d4.png">
