### ISSUE TITLE
Where does it download the package file to?

### ISSUE THREAD

**Issue by ioitall** [scriptingosx/DownloadFullInstaller#7]
I am trying to find where the pkg file was downloaded to. Is there a default location?

**Comment by scriptingosx** [comment]
The default (and only) location is the `Downloads` folder. When the download is complete, the progress bar should change to a "Show in Finder" button.

**Comment by TheQL** [comment]
Is there a temporary location before the download is complete? I have an aborted download and fear it's not cleaned up.

**Comment by scriptingosx** [comment]
A reboot should clean it up.
